CompanyOpenInvoice:
    pattern: /openinvoices/{uid}/{cid}
    defaults: { _controller: DellaertDCIMBundle:Statistics:openInvoices}
    requirements:
        cid: \d+
        uid: \d+

CompanyVat:
    pattern: /vat
    defaults: { _controller: DellaertDCIMBundle:Statistics:vat}

CompanyRevenueExpenses:
    pattern: /companyrevenueexpenses
    defaults: { _controller: DellaertDCIMBundle:Statistics:companyRevenueExpenses}

CompanyRevenueExpensesByYear:
    pattern: /companyrevenueexpensesbyyear/{id}/{year}
    defaults: { _controller: DellaertDCIMBundle:Statistics:companyRevenueExpensesByYear}
    requirements:
        id: \d+
        year: \d+

CompanyVatByYear:
    pattern: /vatbyyear/{id}/{year}
    defaults: { _controller: DellaertDCIMBundle:Statistics:vatByYear}
    requirements:
        id: \d+
        year: \d+

CompanyLastActivity:
    pattern: /lastactivity/{mode}/{back}
    defaults: { _controller: DellaertDCIMBundle:Statistics:lastActivity}
    requirements:
        back: \d+

CompanyActivity:
    pattern: /activity/
    defaults: { _controller: DellaertDCIMBundle:Statistics:activity}

PersonalRevenueExpenses:
    pattern: /personalrevenueexpenses
    defaults: { _controller: DellaertDCIMBundle:Statistics:personalRevenueExpenses}

PersonalRevenueExpensesByYear:
    pattern: /personalrevenueexpensesbyyear/{id}/{year}
    defaults: { _controller: DellaertDCIMBundle:Statistics:personalRevenueExpensesByYear}
    requirements:
        id: \d+
        year: \d+